### ISSUE TITLE
Support vlang.io

### ISSUE THREAD

**Issue by Marcisbee** [pkgxdev/pantry#132]
Any plans to add support for https://vlang.io ?

**Comment by mxcl** [comment]
I gave it a quick go and their “compiling for source” instructions are just wrong.

```yaml
distributable:
  url: https://github.com/vlang/v/archive/refs/tags/{{version}}.tar.gz
  strip-components: 1

versions:
  github: vlang/v/releases

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    make
```

gives errors that suggest `make` is not really enough.
