### ISSUE TITLE
python-tk

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#2307]
How do I get [python-tk](https://formulae.brew.sh/formula/python-tk@3.10#default)? I tried to build this myself but I think I'm getting in over my head.

**Comment by magnusviri** [comment]
It looks like it is supposed to be part of Python. But it requires tkl.tk/tcl. I got over my head with all of the variables in this code:

```
                tcltk_version = Formula["tcl-tk"].any_installed_version.major_minor
                ...
                Extension("_tkinter", ["_tkinter.c", "tkappinit.c"],
                          define_macros=[("WITH_APPINIT", 1)],
                          include_dirs=["#{Formula["tcl-tk"].opt_include/"tcl-tk"}"],
                          libraries=["tcl#{tcltk_version}", "tk#{tcltk_version}"],
                          library_dirs=["#{Formula["tcl-tk"].opt_lib}"])
              ]
```

**Comment by jhheider** [comment]
Hopefully most of those are automatic. It looks like they equate to:
```
env:
  WITH_APPINIT: 1
  CFLAGS:
    - -I {{deps.tcl.tk/tcl.prefix}}/include  ## should be handled by tea automatically
    - -l tcl{{deps.tcl.tk/tcl.version.marketing}}
    - -l tk{{deps.tcl.tk/tcl.version.marketing}}
    - -L {{deps.tcl.tk/tcl.prefix}}/lib      ## should be handled by tea automatically
```
