### ISSUE TITLE
`tea.xyz/gx/cc` should be shims, rather than symlinks, on linux

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/pantry#2742]
Otherwise, they stay locked to the `llvm.org/v*/bin/*` binaries, meaning subsequently doing this doesn't work:
```yaml
dependencies:
  tea.xyz/gx/cc: ^0
  llvm.org: <16
```
