### ISSUE TITLE
Example from building a particular commit SHA rather than tag/release?

### ISSUE THREAD

**Issue by kevinmichaelchen** [pkgxdev/pantry#3081]

**Comment by jhheider** [comment]
Can't easily search from my phone, but if you search pantry for `/commit/`, you'll probably find a few. Explicit calver for the version, and explicit commit for the URL.

**Comment by kevinmichaelchen** [comment]
[**Here's**](https://github.com/teaxyz/pantry/pull/3092) what I landed on.

```yaml
distributable:
  url: https://github.com/ajmwagar/stego/archive/d9d5911f4d2d141fea74936f235a74bf03961c71.zip
  strip-components: 1

versions:
  - 0.0.0
  # FIXME once there has been an official release

build:
  # We normally don't need to do this for tarball releases.
  # ${project_name}-${commit_sha}
  working-directory: stego-d9d5911f4d2d141fea74936f235a74bf03961c71
```
