### ISSUE TITLE
debug version parsing?

### ISSUE THREAD

**Issue by tannevaled** [pkgxdev/pantry#3705]
Hi,

i try to package portable-openssh
i thought the version parsing would be easy but it seems it does not work as expected.

```yaml
versions:
  url: https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/
  match: /.*\.tar\.gz/
  strip:
    - /^openssh-/
    - /.tar.gz$/
distributable:
  url: https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-{{version}}.tar.gz
  strip-components: 1
...
```

```bash
$ VERBOSE=1 DEBUG=1 pkg build openssh.com
...
 building openssh.com
++ resolve.ts openssh.com
{ versions: [] }
error: Uncaught Error: not-found: version: openssh.com
    throw new Error(`not-found: version: ${utils.pkg.str(spec)}`)
          ^
    at Object.resolve (file:///home/dd.linux/.pkgx/pkgx.sh/brewkit/v0.46.4/lib/usePantry.ts:43:11)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///home/dd.linux/.pkgx/pkgx.sh/brewkit/v0.46.4/libexec/resolve.ts:15:15
+ PKG=
```

Is there a way to really debug the version parsing?

**Comment by jhheider** [comment]
I think what you're seeing is what's implemented at the moment. But the bug in your version key is visible to me:
```yaml
  match: /.*\.tar\.gz/
```
is going to greedy-match way too much stuff. you want:
```yaml
  match: /openssh-\d+\.\d+p1\.tar\.gz/
    strip:
    - /^openssh-/
    - /p1.tar.gz$/
```

**Comment by tannevaled** [comment]
in fact you can have something like **openssh-9.3p2.tar.gz**

```yaml
 match: /openssh-\d+\.\d+p\d+\.tar\.gz/
 strip:
    - /^openssh-/
    - /.tar.gz$/
```
does not work.
