### ISSUE TITLE
Creating an LTS tag for node js

### ISSUE THREAD

**Issue by kishaningithub** [pkgxdev/pantry#3954]
When I am using NVM my general usage is to run `nvm install --lts` to ensure I use the latest node LTS version in my project 

It would be great if I can do something like `pkgx node@lts --version` and use the latest LTS version

**Comment by jhheider** [comment]
it's an interesting idea. what you'd want to implement would be something like:
```yaml
versions:
  github: nodejs/node/releases/tags
  aliases:
    lts: ^24 || ^22 || ^20 || ^18 || ^16
```
or similar. I believe that support would be in `pkgxdev/libpkgx`. I'll move this issue there for further exploration.
