### ISSUE TITLE
Missing: /opt/pkgx/ruby-lang.org/v3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#4010]
I'm trying to package up [gollum](https://github.com/gollum/gollum), which is written in Ruby. I don't know much about building Ruby projects. I'm hoping someone can help. Here's my package.yml and the error.

```
distributable:
  url: https://github.com/gollum/gollum/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: gollum/gollum/tags

dependencies:
  ruby-lang.org: ^3.1
  rubygems.org: '*'

build:
  dependencies:
    ruby-lang.org: ^3.1
  script: |
    bundle install
    bundle exec bin/gollum

provides:
  - bin/gollum
```

This is the error:

```
+ bundle install
/opt/pkgx/rubygems.org/v3.4.21/shim/bundle:25:in `load': cannot load such file -- /opt/pkgx/ruby-lang.org/v3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle (LoadError)
	from /opt/pkgx/rubygems.org/v3.4.21/shim/bundle:25:in `<main>'
```

/opt/pkgx/ruby-lang.org/v3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10 does not exist. I don't know enough to know why or what to even try to fix it.
