### ISSUE TITLE
What is the correct way to add `runtime.env.FOO` in package.yml?

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#491]
I need to add a runtime environment variable `TESSDATA_PREFIX` to my package #454 

```yaml
...
runtime:
  env:
    TESSDATA_PREFIX: "{{prefix}}"/share/tessdata/
...
``` 

However, it doesn't like this format and `pkg test` throws the following **error**:
```
tesseract-ocr.github.io: can not read an implicit mapping pair; a colon is missed at line 17, column 50:
     ... IX: "{{prefix}}"/share/tessdata/
```

**Comment by mxcl** [comment]
it's not valid YAML with the quotes ending midstring. You need:

```yaml
runtime:
  env:
    TESSDATA_PREFIX: "{{prefix}}/share/tessdata/"
```

https://yamlchecker.com is useful
