### ISSUE TITLE
Ansible is missing paramiko

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#494]
@ddobrinskiy 

When I run Ansible specifying the paramiko connection I get the following error.

```
  comp110-01 failed | msg: paramiko is not installed: No module named 'paramiko'
```

I fixed it with `~/.tea/ansible.com/v2.14.3/venv/bin/pip3 install paramiko`. You can use this playbook to test (changing the name of the hosts). I'd submit a pull request but I'm so backlogged on things (I still need to make a pull request for something else I've packaged, I just haven't had the time).

```
- hosts: *name*
  gather_facts: no
  connection: paramiko
  tasks:
  - name: Name
    shell: hostname
```
