### ISSUE TITLE
+itstool (119/548)

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#532]
Formulae: https://formulae.brew.sh/formula/itstool

**Comment by sanchitram1** [comment]
Packaging this and running into an issue about the availability of `libxml2`.   My guess is that this python requires the `libxml2` package in the python/lib/site-packages directory, so I tried including a step for `pip install lxml`, but still ran into the same errors.

Here's the error that happens in my `./configure` step:

```sh
+ ./configure --prefix=/Users/sanch/.tea/itstool/v2.0.7 --without-python --without-plugins
configure: WARNING: unrecognized options: --without-python, --without-plugins
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for a Python interpreter with version >= 2.6... python
checking for python... /Users/sanch/.tea/python.org/v3.11.2/bin/python
checking for python version... 3.11
checking for python platform... darwin
checking for python script directory... ${prefix}/lib/python3.11/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.11/site-packages
checking for python module libxml2... not found
configure: error: Python module libxml2 is needed to run this package
```

Here's the script and build dependencies in the yaml file:
```yaml
build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    gnome.org/libxml2: '*'
    freedesktop.org/pkg-config: '*'
    # ^^ often packages need dependencies to build, it is very common for
    # packages to need a C compiler and make, the above provide those
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }}
    make install
  # it’s extremely common for packages to require the above
  env:
    # add any environment variables here
    ARGS:
      - --prefix="{{prefix}}"
      - --without-python
      - --without-plugins 
```

**Comment by sanchitram1** [comment]
@mfts was able to make `libxml2` build by removing the `--without-python` flag, by making the following updates.  I added `pkg-config` and `python` as build dependencies
```yaml
build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    freedesktop.org/pkg-config: '*'
    python.org: ^3.9
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }}
    make install

    cd {{prefix}}/bin
    sed -i.bak 's|{{prefix}}|"$(cd "$(dirname "$0")/.." \&\& pwd)"|' xml2-config
    rm *.bak
  env:
    ARGS:
      - --prefix={{prefix}}
      - --without-lzma
 ```

Still not getting `itstool` to work though...
