### ISSUE TITLE
pip depends on python ^3.7

### ISSUE THREAD

**Issue by mxcl** [pkgxdev/pantry#761]
This makes it impossible to use pip with python < 3.7.

Assigning to Jacob for explanation since he wrote this and didn't leave a comment explaining himself at the time.

**Comment by jhheider** [comment]
Current version requirement: https://pip.pypa.io/en/stable/installation/#compatibility

I believe we'd need some kind of paired dependency ladder to relax that requirement while still ensuring compatibility.

**Comment by jhheider** [comment]
maybe:
```yaml
dependencies:
  python.org:
    '^22': '>=3.7'
    '^20': '>=2.7 <3.9'
```
