### ISSUE TITLE
+ngpost

### ISSUE THREAD

**Issue by davdroman** [pkgxdev/pantry#7916]
Would be great to have https://github.com/mbruel/ngPost

**Comment by jhheider** [comment]
doesn't look too difficult. the base `package.yml` is

```yaml
distributable:
  url: https://github.com/mbruel/ngPost/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: mbruel/ngPost

provides:
  - bin/ngPost

build:
  dependencies:
    qt.io: 5
    openssl.org: '*'
  working-directory: src
  script:
    - qmake
    - make
    # move bin to {{prefix}}

test: ngPost --help
```

it looks like it will require `par2` and `rar` to be packaged first.

**Comment by jhheider** [comment]
more progress, but hitting macos framework errors. here's the WIP if anyone wants to touch it:
```yaml
distributable:
  url: https://github.com/mbruel/ngPost/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: mbruel/ngPost

provides:
  - bin/ngPost

dependencies:
  qt.io: 5
  openssl.org: '*'

build:
  dependencies:
    github.com/Parchive/par2cmdline: '*' # gets vendored in
    # parpar binaries
    curl.se: '*'
    tukaani.org/xz: '*'
  working-directory: src
  script:
    - cp {{deps.github.com/Parchive/par2cmdline.prefix}}/bin/par2 .
    - curl -L -o parpar.xz $PARPAR
    - xz -d --force parpar.xz
    - qmake
    - make
    - run:
        - mkdir bin libexec
        - cp -a $SRCROOT/src/ngPost.app libexec/
        - ln -s ../libexec/ngPost.app/Contents/MacOS/ngPost bin/ngPost
        - install_name_tool -add_rpath @loader_path/../../../../../../../.. libexec/ngPost.app/Contents/MacOS/ngPost

      working-directory: '{{prefix}}'
      if: darwin
  skip: fix-machos

  env:
    linux/x86-64:
      PARPAR: https://github.com/animetosho/ParPar/releases/download/v0.4.3/parpar-v0.4.3-linux-static-amd64.xz
    linux/aarch64:
      PARPAR: https://github.com/animetosho/ParPar/releases/download/v0.4.3/parpar-v0.4.3-linux-static-aarch64.xz
    # no aarch64 bins for macos
    darwin:
      PARPAR: https://github.com/animetosho/ParPar/releases/download/v0.4.3/parpar-v0.4.3-macos-x64.xz

test: ngPost --help
```

needs: https://github.com/pkgxdev/pantry/pull/7968
