### ISSUE TITLE
+pnpm.io

### ISSUE THREAD

**Issue by mxcl** [pkgxdev/pantry#8]

**Comment by pedrocruzio** [comment]
@mxcl here's a WIP:

```
distributable:
  url: https://github.com/pnpm/pnpm/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1
  
versions:
  github: pnpm/pnpm

provides:
  - bin/pnpm
  - bin/pnpx

dependencies:
  nodejs.org: '>=14'

build:
  dependencies:
    curl.se: '*'
  script: |
    curl -fsSL https://get.pnpm.io/install.sh | sh -

test:
  script: |
    pnpm --help
```
